// Code generated by Slice Machine. DO NOT EDIT.

import ArticleLeadParagraph from './ArticleLeadParagraph';

export {
	ArticleLeadParagraph,
};

export const components = {
	article_lead_paragraph: ArticleLeadParagraph,
};
