// Code generated by Slice Machine. DO NOT EDIT.

import ArticleLeadParagraph from './ArticleLeadParagraph';
import Faq from './Faq';

export {
	ArticleLeadParagraph,
	Faq,
};

export const components = {
	article_lead_paragraph: ArticleLeadParagraph,
	faq: Faq,
};
